# Config of a 4x4 mesh with high error parameters for NACK testing
topology: MESH
mesh_dim_x: 4
mesh_dim_y: 4
buffer_depth: 4
flit_size: 32
r2h_link_length: 2.0
r2r_link_length: 1.0
n_virtual_channels: 1
routing_algorithm: XY
routing_table_filename: ""
dyad_threshold: 0.6
selection_strategy: RANDOM
clock_period_ps: 1000
reset_time: 1000
simulation_time: 10000
stats_warm_up_time: 1000
detailed: false
max_volume_to_be_drained: 0
show_buffer_stats: false
verbose_mode: VERBOSE_MEDIUM
trace_mode: false
trace_filename: ""
min_packet_size: 8
max_packet_size: 8
packet_injection_rate: 0.01
traffic_distribution: TRAFFIC_RANDOM
traffic_table_filename: "t.txt"

# LIGHT FATIGUE CONFIGURATION
default_delay_status: 0
max_delay_cycles: 50
delay_increase_probability: 0.001
delay_decrease_probability: 0.0005

# ERROR AND ENCODING FOR NACK TESTING
encoding_model: HAMMING
wired_bit_error_rate: 0.01
wireless_bit_error_rate: 0.01
